spring:
  application:
    name: dubbo_provider
server:
  port: 8080
#指定当前服务/应用的名字（同样的服务名字相同，不要和别的服务同名）
dubbo:
  application:
    name: dubbo_provider
  protocol:
    name: dubbo
    port: 20880
#指定注册中心的位置
  registry:
    address: zookeeper://123.206.19.217:2181
    check: false
  monitor:
    protocol: register
